vcf_wld_hostname: "sddc-manager.{{ lab_domain }}"
vcf_wld_username: admin@local
vcf_wld_password: "{{ sddc_admin_password }}"

vcf_wld_hosts:
  - fqdn: "esxi-05.{{ lab_domain }}"
    username: root
    password: "{{ bootstrap_password }}"
    storageType: VSAN_ESA
  - fqdn: "esxi-06.{{ lab_domain }}"
    username: root
    password: "{{ bootstrap_password }}"
    storageType: VSAN_ESA
  - fqdn: "esxi-07.{{ lab_domain }}"
    username: root
    password: "{{ bootstrap_password }}"
    storageType: VSAN_ESA

vcf_wld_domain_spec:
  domainName: workload-domain
  deployWithoutLicenseKeys: true
  ssoDomainSpec:
    ssoDomainName: vsphere.local
    ssoDomainPassword: "{{ vcf_wld_password }}"
  vcenterSpec:
    name: vcenter-wld
    networkDetailsSpec:
      ipAddress: "{{ host_ip['vcenter-wld'] }}"
      dnsName: "vcenter-wld.{{ lab_domain }}"
      gateway: "{{ vlan['management'].gateway }}"
      subnetMask: 255.255.255.0
    rootPassword: "{{ vcf_wld_password }}"
    datacenterName: workload-dc
    vmSize: SMALL
    storageSize: lstorage
  computeSpec:
    clusterSpecs:
      - name: workload-cluster
        clusterImageId: "{{ cluster_image_id }}"
        hostSpecs: "{{ vcf_wld_host_specs }}"
        datastoreSpec:
          vsanDatastoreSpec:
            datastoreName: workload-vsan-ds
            esaConfig:
              enabled: true
        networkSpec:
          vdsSpecs:
            - name: workload-cluster-vds01
              portGroupSpecs:
                - name: workload-cluster-vds01-pg-mgmt
                  transportType: MANAGEMENT
                  teamingPolicy: loadbalance_loadbased
                  activeUplinks:
                    - uplink1
                  standByUplinks: []
                - name: workload-cluster-vds01-pg-vmotion
                  transportType: VMOTION
                  teamingPolicy: loadbalance_loadbased
                  activeUplinks:
                    - uplink1
                  standByUplinks: []
                - name: workload-cluster-vds01-pg-vsan
                  transportType: VSAN
                  teamingPolicy: loadbalance_loadbased
                  activeUplinks:
                    - uplink1
                  standByUplinks: []
              nsxtSwitchConfig:
                hostSwitchOperationalMode: STANDARD
                transportZones:
                  - name: workload-vlan-tz
                    transportType: VLAN
                  - name: workload-overlay-tz
                    transportType: OVERLAY
          nsxClusterSpec:
            nsxTClusterSpec:
              geneveVlanId: "{{ vlan['host_overlay'].vlan_id }}"
              ipAddressPoolSpec:
                name: workload-tep-pool
                subnets:
                  - ipAddressPoolRanges:
                      - start: "{{ ip_pool['workload-tep-pool'].start_ip }}"
                        end: "{{ ip_pool['workload-tep-pool'].end_ip }}"
                    cidr: "{{ ip_pool['workload-tep-pool'].subnet }}"
                    gateway: "{{ ip_pool['workload-tep-pool'].gateway }}"
  nsxTSpec:
    vipFqdn: "nsx-vip-wld.{{ lab_domain }}"
    nsxManagerSpecs:
      - name: nsx-mgr-wld
        networkDetailsSpec:
          dnsName: "nsx-mgr-wld.{{ lab_domain }}"
          ipAddress: "{{ host_ip['nsx-mgr-wld'] }}"
          gateway: "{{ vlan['management'].gateway }}"
          subnetMask: 255.255.255.0
    nsxManagerAdminPassword: "{{ nsx_admin_password }}"
    formFactor: medium
