vcf_wld_hostname: "sddc-manager.{{ lab_domain }}"
vcf_wld_username: admin@local
vcf_wld_password: "{{ sddc_admin_password }}"

vcf_wld_hosts:
  - fqdn: "esxi-05.{{ lab_domain }}"
    username: root
    password: "{{ bootstrap_password }}"
    storageType: VSAN_ESA
  - fqdn: "esxi-06.{{ lab_domain }}"
    username: root
    password: "{{ bootstrap_password }}"
    storageType: VSAN_ESA
  - fqdn: "esxi-07.{{ lab_domain }}"
    username: root
    password: "{{ bootstrap_password }}"
    storageType: VSAN_ESA

vcf_wld_domain_spec:
  domainName: workload-domain
  networkSpec:
    - networkType: MANAGEMENT
      subnet: "{{ vlans.management.subnet }}"
      gateway: "{{ vlans.management.gateway }}"
      vlanId: "{{ vlans.management.id }}"
      mtu: "{{ vlans.management.mtu }}"
    - networkType: VMOTION
      subnet: "{{ vlans.vmotion.subnet }}"
      gateway: "{{ vlans.vmotion.gateway }}"
      vlanId: "{{ vlans.vmotion.id }}"
      mtu: "{{ vlans.vmotion.mtu }}"
      includeIpAddressRanges:
        - startIpAddress: "{{ lab_vmotion_prefix }}.15"
          endIpAddress: "{{ lab_vmotion_prefix }}.17"
    - networkType: VSAN
      subnet: "{{ vlans.vsan.subnet }}"
      gateway: "{{ vlans.vsan.gateway }}"
      vlanId: "{{ vlans.vsan.id }}"
      mtu: "{{ vlans.vsan.mtu }}"
      includeIpAddressRanges:
        - startIpAddress: "{{ lab_vsan_prefix }}.15"
          endIpAddress: "{{ lab_vsan_prefix }}.17"
  vcenterSpec:
    name: vcenter-wld
    networkDetailsSpec:
      ipAddress: "{{ lab_mgmt_prefix }}.9"
      dnsName: "vcenter-wld.{{ lab_domain }}"
      gateway: "{{ lab_gateway }}"
      subnetMask: 255.255.255.0
    rootPassword: "{{ vcf_wld_password }}"
  nsxTSpec:
    nsxManagerSpecs:
      - name: nsx-mgr-wld
        networkDetailsSpec:
          ipAddress: "{{ lab_mgmt_prefix }}.10"
          dnsName: "nsx-mgr-wld.{{ lab_domain }}"
          gateway: "{{ lab_gateway }}"
          subnetMask: 255.255.255.0
    nsxManagerAdminPassword: "{{ nsx_admin_password }}"
  computeSpec:
    clusterSpecs:
      - name: workload-cluster
        hostSpecs: "{{ vcf_wld_hosts }}"
        datastoreSpec:
          vsanDatastoreSpec:
            datastoreName: workload-vsan-ds
            esaEnabled: true
