all:
  children:
    jumpbox:
      hosts:
        jumpbox:
          ansible_host: 127.0.0.1
          ansible_connection: local
    veos:
      hosts:
        veos-router:
          ansible_host: 10.0.10.1
          ansible_network_os: arista.eos.eos
          ansible_become: true
          ansible_become_method: enable
    esxi:
      vars:
        ansible_user: root
        ansible_password: "{{ lookup('community.hashi_vault.vault_kv2_get', 'esxi/root-password', engine_mount_point='secret', url=openbao_url, token=openbao_token).secret.value }}"
      children:
        esxi_management:
          hosts:
            esxi-01:
              ansible_host: 10.0.10.11
              esxi_mac: "00:50:56:xx:xx:01"
            esxi-02:
              ansible_host: 10.0.10.12
              esxi_mac: "00:50:56:xx:xx:02"
            esxi-03:
              ansible_host: 10.0.10.13
              esxi_mac: "00:50:56:xx:xx:03"
            esxi-04:
              ansible_host: 10.0.10.14
              esxi_mac: "00:50:56:xx:xx:04"
        esxi_workload:
          hosts:
            esxi-05:
              ansible_host: 10.0.10.15
              esxi_mac: "00:50:56:xx:xx:05"
            esxi-06:
              ansible_host: 10.0.10.16
              esxi_mac: "00:50:56:xx:xx:06"
            esxi-07:
              ansible_host: 10.0.10.17
              esxi_mac: "00:50:56:xx:xx:07"
    vcf_appliances:
      hosts:
        vcf-installer:
          ansible_host: 10.0.10.3
        vcenter-mgmt:
          ansible_host: 10.0.10.4
        sddc-manager:
          ansible_host: 10.0.10.5
        nsx-mgr-mgmt:
          ansible_host: 10.0.10.6
        vcenter-wld:
          ansible_host: 10.0.10.9
        nsx-mgr-wld:
          ansible_host: 10.0.10.10
    nsx_edges:
      hosts:
        edge-01:
          ansible_host: 10.0.10.20
          edge_tep_ip: 10.0.50.20
        edge-02:
          ansible_host: 10.0.10.21
          edge_tep_ip: 10.0.50.21
