vcf_mgmt_hostname: "sddc-manager.{{ lab_domain }}"
vcf_mgmt_username: admin@local
vcf_mgmt_password: "{{ sddc_admin_password }}"

vcf_mgmt_components_spec:
  vcfOperationsSpec:
    nodes:
      - hostname: "vcf-ops.{{ lab_domain }}"
        type: master
        rootUserPassword: "{{ sddc_admin_password }}"
    adminUserPassword: "{{ sddc_admin_password }}"
    applianceSize: xsmall
  vcfOperationsCollectorSpec:
    hostname: "vcf-ops-collector.{{ lab_domain }}"
    rootUserPassword: "{{ sddc_admin_password }}"
    applianceSize: small
  vcfOperationsFleetManagementSpec:
    hostname: "vcf-ops-fleet.{{ lab_domain }}"
    rootUserPassword: "{{ sddc_admin_password }}"
    adminUserPassword: "{{ sddc_admin_password }}"
  vcfMangementComponentsInfrastructureSpec:
    localRegionNetwork:
      networkName: vcf-m01-cl01-vds01-pg-vm-mgmt
      subnetMask: 255.255.255.0
      gateway: "{{ vlan['management'].gateway }}"
    xRegionNetwork:
      networkName: vcf-m01-cl01-vds01-pg-vm-mgmt
      subnetMask: 255.255.255.0
      gateway: "{{ vlan['management'].gateway }}"
