vcf_bringup_hostname: "vcf-installer.{{ lab_domain }}"
vcf_bringup_username: admin@local
vcf_bringup_password: "{{ sddc_admin_password }}"

vcf_bringup_depot_spec:
  offlineAccount:
    username: "{{ depot_username }}"
    password: "{{ depot_password }}"
  depotConfiguration:
    isOfflineDepot: true
    hostname: "{{ vcf_depot_url }}"
    port: 443

vcf_bringup_spec:
  sddcId: vcf-m01
  workflowType: VCF
  ceipEnabled: false
  skipEsxThumbprintValidation: true
  managementPoolName: mgmt-network-pool
  dnsSpec:
    nameservers:
      - "{{ host_ip['gateway'] }}"
    subdomain: "{{ lab_domain }}"
  ntpServers:
    - "{{ host_ip['gateway'] }}"
  vcenterSpec:
    vcenterHostname: "vcenter-mgmt.{{ lab_domain }}"
    rootVcenterPassword: "{{ vcenter_sso_password }}"
    adminUserSsoPassword: "{{ vcenter_sso_password }}"
    vmSize: small
    storageSize: lstorage
    ssoDomain: vsphere.local
  clusterSpec:
    clusterName: vcf-m01-cl01
    datacenterName: vcf-m01-dc01
  datastoreSpec:
    vsanSpec:
      datastoreName: vcf-m01-cl01-ds-vsan01
      esaConfig:
        enabled: true
  sddcManagerSpec:
    hostname: "sddc-manager.{{ lab_domain }}"
    rootPassword: "{{ sddc_admin_password }}"
    sshPassword: "{{ sddc_admin_password }}"
    localUserPassword: "{{ sddc_admin_password }}"
  nsxtSpec:
    nsxtManagerSize: medium
    rootNsxtManagerPassword: "{{ nsx_admin_password }}"
    nsxtAdminPassword: "{{ nsx_admin_password }}"
    nsxtAuditPassword: "{{ nsx_admin_password }}"
    skipNsxOverlayOverManagementNetwork: true
    nsxtManagers:
      - hostname: "nsx-mgr-mgmt-01.{{ lab_domain }}"
    vipFqdn: "nsx-mgr-mgmt.{{ lab_domain }}"
    transportVlanId: "{{ vlan['host_overlay'].vlan_id }}"
    ipAddressPoolSpec:
      name: tep-ip-pool
      description: ESXi Host Overlay TEP IP Pool
      subnets:
        - cidr: "{{ ip_pool['tep-ip-pool'].subnet }}"
          gateway: "{{ ip_pool['tep-ip-pool'].gateway }}"
          ipAddressPoolRanges:
            - start: "{{ ip_pool['tep-ip-pool'].start_ip }}"
              end: "{{ ip_pool['tep-ip-pool'].end_ip }}"
  hostSpecs:
    - hostname: esxi-01
      credentials:
        username: root
        password: "{{ bootstrap_password }}"
    - hostname: esxi-02
      credentials:
        username: root
        password: "{{ bootstrap_password }}"
    - hostname: esxi-03
      credentials:
        username: root
        password: "{{ bootstrap_password }}"
    - hostname: esxi-04
      credentials:
        username: root
        password: "{{ bootstrap_password }}"
  networkSpecs:
    - networkType: MANAGEMENT
      subnet: "{{ vlan['management'].subnet }}"
      gateway: "{{ vlan['management'].gateway }}"
      vlanId: "{{ vlan['management'].vlan_id }}"
      mtu: "{{ vlan['management'].mtu }}"
      portGroupKey: vcf-m01-cl01-vds01-pg-mgmt
      teamingPolicy: loadbalance_loadbased
      activeUplinks:
        - uplink1
      standbyUplinks: []
    - networkType: VM_MANAGEMENT
      subnet: "{{ vlan['management'].subnet }}"
      gateway: "{{ vlan['management'].gateway }}"
      vlanId: "{{ vlan['management'].vlan_id }}"
      mtu: "{{ vlan['management'].mtu }}"
      portGroupKey: vcf-m01-cl01-vds01-pg-vm-mgmt
      teamingPolicy: loadbalance_loadbased
      activeUplinks:
        - uplink1
      standbyUplinks: []
    - networkType: VMOTION
      subnet: "{{ vlan['vmotion'].subnet }}"
      gateway: "{{ vlan['vmotion'].gateway }}"
      vlanId: "{{ vlan['vmotion'].vlan_id }}"
      mtu: "{{ vlan['vmotion'].mtu }}"
      portGroupKey: vcf-m01-cl01-vds01-pg-vmotion
      teamingPolicy: loadbalance_loadbased
      activeUplinks:
        - uplink1
      standbyUplinks: []
      includeIpAddressRanges:
        - startIpAddress: "{{ ip_pool['mgmt-vmotion'].start_ip }}"
          endIpAddress: "{{ ip_pool['mgmt-vmotion'].end_ip }}"
    - networkType: VSAN
      subnet: "{{ vlan['vsan'].subnet }}"
      gateway: "{{ vlan['vsan'].gateway }}"
      vlanId: "{{ vlan['vsan'].vlan_id }}"
      mtu: "{{ vlan['vsan'].mtu }}"
      portGroupKey: vcf-m01-cl01-vds01-pg-vsan
      teamingPolicy: loadbalance_loadbased
      activeUplinks:
        - uplink1
      standbyUplinks: []
      includeIpAddressRanges:
        - startIpAddress: "{{ ip_pool['mgmt-vsan'].start_ip }}"
          endIpAddress: "{{ ip_pool['mgmt-vsan'].end_ip }}"
  dvsSpecs:
    - dvsName: vcf-m01-cl01-vds01
      networks:
        - MANAGEMENT
        - VM_MANAGEMENT
        - VMOTION
        - VSAN
      mtu: 8900
      nsxtSwitchConfig:
        hostSwitchOperationalMode: STANDARD
        transportZones:
          - name: nsx-vlan-transportzone
            transportType: VLAN
          - name: overlay-tz-vcf-m01
            transportType: OVERLAY
      vmnicsToUplinks:
        - id: vmnic0
          uplink: uplink1
      nsxTeamings:
        - policy: LOADBALANCE_SRCID
          standByUplinks: []
          activeUplinks:
            - uplink1
