esxi_dns_server: "{{ lab_dns_server }}"
esxi_domain: "{{ lab_domain }}"
esxi_ntp_servers: "{{ lab_ntp_servers }}"
esxi_gateway: "{{ lab_gateway }}"
esxi_ca_cert_path: "{{ lookup('env', 'HOME') }}/.lab-root-ca.crt"
