vcf_ops_hostname: "vcf-ops.{{ lab_domain }}"
vcf_ops_username: admin
vcf_ops_password: "{{ sddc_admin_password }}"
vcf_sso_model: EMBEDDED
vcf_automation_deployed: false

vcf_oidc_label: Keycloak
vcf_oidc_discovery_url: "https://gateway.{{ lab_domain }}:8443/realms/{{ keycloak_realm }}/.well-known/openid-configuration"
vcf_oidc_client_id: vcf-identity-broker
vcf_oidc_client_secret: "{{ keycloak_admin_password }}"
vcf_oidc_domain: "{{ lab_domain }}"
vcf_oidc_jit_group: vcf-admins
vcf_oidc_group_attr: groups
vcf_oidc_cert_path: "{{ ca_cert_path }}"
