---
- name: apply netplan
  become: true
  ansible.builtin.shell: netplan apply
  changed_when: true

- name: restart dnsmasq
  become: true
  ansible.builtin.service:
    name: dnsmasq
    state: restarted

- name: restart chrony
  become: true
  ansible.builtin.service:
    name: chrony
    state: restarted

- name: save iptables
  become: true
  ansible.builtin.shell: netfilter-persistent save
  changed_when: true

- name: restart frr
  become: true
  ansible.builtin.service:
    name: frr
    state: restarted

- name: restart step-ca
  become: true
  ansible.builtin.service:
    name: step-ca
    state: restarted

- name: restart gdm3
  become: true
  ansible.builtin.service:
    name: gdm3
    state: restarted

- name: restart xrdp
  become: true
  ansible.builtin.service:
    name: xrdp
    state: restarted
